services:
  backend:
    build: ./app
    container_name: fokus_backend
    restart: always
    ports:
      - "8050:8000"
    volumes:
      - ./app:/app
    environment:
      - API_KEY=fokusistatistik

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://python.fokusistatistik.com/api
        CACHE_BUST: "${CACHE_BUST:-3}"
    container_name: fokus_frontend
    restart: always
    ports:
      - "3050:3000"
    depends_on:
      - backend
