version: '3.8'

services:
  backend:
    build: ./app
    container_name: fokus_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - API_KEY=fokusistatistik

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://python.fokusistatistik.com/api
    container_name: fokus_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: fokus_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
