name: Deploy to VPS

on:
  push:
    branches: [ "test" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 145.223.85.215
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
            # Create directory if not exists
            mkdir -p /root/python-api
            cd /root/python-api

            # Clone or Pull
            if [ -d ".git" ]; then
              git pull https://github.com/fokusistatistik/python.git test
            else
              git clone -b test https://github.com/fokusistatistik/python.git .
            fi
            
            # Deploy
            docker-compose down
            docker-compose up -d --build
