name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 145.223.85.215
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Create directory if not exists
            mkdir -p /opt/fokus-istatistik
            cd /opt/fokus-istatistik

            # Clone or Pull
            if [ -d ".git" ]; then
              git pull https://github.com/fokusistatistik/python.git main
            else
              git clone https://github.com/fokusistatistik/python.git .
            fi
            
            # Deploy
            docker-compose down
            docker-compose up -d --build
